ABE.mean <- sum(ABE$Data)/length(ABE$Data)
ACC.mean <- sum(ACC$Data)/length(ACC$Data)
AKA.mean <- sum(AKA$Data)/length(AKA$Data)
ADA.mean <- sum(ADA$Data)/length(ADA$Data)
AXM.mean <- sum(AXM$Data)/length(AXM$Data)
BEK.mean <- sum(BEK$Data)/length(BEK$Data)
BOL.mean <- sum(BOL$Data)/length(BOL$Data)
HO.mean <- sum(HO$Data)/length(HO$Data)
KDA.mean <- sum(KDA$Data)/length(KDA$Data)
KRA.mean <- sum(KRA$Data)/length(KRA$Data)
KSI.mean <- sum(KSI$Data)/length(KSI$Data)
NAV.mean <- sum(NAV$Data)/length(NAV$Data)
NAV1.mean <- sum(NAV1$Data)/length(NAV1$Data)
ODA.mean <- sum(ODA$Data)/length(ODA$Data)
SAL.mean <- sum(SAL$Data)/length(SAL$Data)
SUN.mean <- sum(SUN$Data)/length(SUN$Data)
TDI.mean <- sum(TDI$Data)/length(TDI$Data)
TEM.mean <- sum(TEM$Data)/length(TEM$Data)
TLE.mean <- sum(TLE$Data)/length(TLE$Data)
WA.mean <- sum(WA$Data)/length(WA$Data)
WEN.mean <- sum(WEN$Data)/length(WEN$Data)

ABE.Amean <- sum(ABE$Data)/28
ACC.Amean <- sum(ACC$Data)/30
AKA.Amean <- sum(AKA$Data)/29
ADA.Amean <- sum(ADA$Data)/30
AXM.Amean <- sum(AXM$Data)/30
BEK.Amean <- sum(BEK$Data)/29
BOL.Amean <- sum(BOL$Data)/30
HO.Amean <- sum(HO$Data)/30
KDA.Amean <- sum(KDA$Data)/30
KRA.Amean <- sum(KRA$Data)/30
KSI.Amean <- sum(KSI$Data)/30
NAV.Amean <- sum(NAV$Data)/30
NAV1.Amean <- sum(NAV1$Data)/30
ODA.Amean <- sum(ODA$Data)/30
SAL.Amean <- sum(SAL$Data)/30
SUN.Amean <- sum(SUN$Data)/30
TDI.Amean <- sum(TDI$Data)/30
TEM.Amean <- sum(TEM$Data)/30
TLE.Amean <- sum(TLE$Data)/30
WA.Amean <- sum(WA$Data)/30
WEN.Amean <- sum(WEN$Data)/30
